services:
  # Servicio 1: Frontend (Página Web Estática)
  - type: web
    name: visor-cementerio
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    branch: main

  # Servicio 2: Backend (GeoServer con Docker)
  - type: web
    name: mi-geoserver
    env: docker
    dockerfilePath: ./geoserver/Dockerfile
    plan: standard # 2GB de RAM para GeoServer
    branch: main
    envVars:
      - key: GEOSERVER_ADMIN_PASSWORD
        value: "myawesomegeoserver"
      - key: GEOSERVER_ADMIN_USER
        value: "admin"
      # Variables de conexión a base de datos de producción (Supabase)
      # - key: POSTGRES_HOST
      #   value: "tu-host-de-supabase.supabase.co"
      # - key: POSTGRES_PORT
      #   value: "5432"
      # - key: POSTGRES_DB
      #   value: "postgres"
      # - key: POSTGRES_USER
      #   value: "postgres"
      # - key: POSTGRES_PASSWORD
      #   value: "tu_contraseña"
